version: '3'

services:
  app:
    build: .
    container_name: nav-uzemanyagar-api
    ports:
      - 5000:5000

  cache:
    image: "redis:alpine"
    container_name: nav-uzemanyagar-api-cache
    ports:
      - 6379:6379

